config/routes.rb
Depot::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :products, :only => [:index, :show]
  resources :line_items, :only => [:create]
  
  get 'search' => 'searches#index'
  get 'about' => 'site#about'

  root :to => "site#index"
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  
  has_many :line_items, :dependent => :destroy
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  
  has_attached_file :image,
                    :url => '/uploads/:class/:id_partition/:style_:basename.:extension',
                    :path => ':rails_root/public/uploads/:class/:id_partition/:style_:basename.:extension',
                    :styles => { :main => '300x350#', :thumb => '50X50>' }
  
  def self.latest
    order('created_at DESC').limit(5)
  end
  
  def self.search(query)
    where("name LIKE ?", "%#{query}%")
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :get_order
  
  
  private
  
    def get_order
      @order ||= current_order
    end
  
    def current_order
      Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
      order = Order.create
      session[:order_id] = order.id
      order
    end
      
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  
  def create
    @product = Product.find(params[:product_id])
    @line_item = current_order.line_items.build(name: @product.name, price: @product.price, quantity: params[:line_item][:quantity])
    if @line_item.save
      redirect_to product_path(@product), notice: "#{@line_item.name} added to your order."
    else
      render @product
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  def show
    @product = Product.find(params[:id])
    @line_item = current_order.line_items.build
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def index
    if params[:q]
      @results = Product.search(params[:q]).page(params[:page]).per(5)
    end
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  def index
    @products = Product.latest
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def link_to_cart(order)
    total_items = order.line_items.count
    if total_items > 0
      count = order.line_items.inject(0) { |sum, li| sum += li.quantity }
      link_to(pluralize(count, 'item') + ' - Checkout', root_path)
    else
      link_to('Cart', root_path)
    end
  end
  
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyWeekend Depot Store</title>
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrapper">
    <div id="header">
      <%= link_to(image_tag(asset_path('rw_depot_theme_logo.png')), root_path, :id => 'logo') %>
      <div id="social">
        <%= link_to(image_tag('twitter-icon.gif') + " Follow Us", 'http://twitter.com', :target => '_blank') %>
        <%= link_to(image_tag('facebook-icon.gif') + " Like Us", 'http://www.facebook.com', :target => '_blank') %>
        <div id="search">
          <%= form_tag('/search', :method => "get") do %>
            <%= text_field_tag(:q) %>
            <%= submit_tag('Search') %>
          <% end %>
        </div>
      </div>
      <br clear="all">
      <div id="navbar">
        <ul id="nav">
          <li><%= link_to('Home', root_path) %></li>
          <li><%= link_to('About', about_path) %></li>
          <li><%= link_to('Products', products_path) %></li>
          <li><%= link_to('Contact Us', root_path) %></li>
          <li><%= link_to_cart(@order) %></li>
        </ul>
      </div>
    </div>
    <div id="content">
      <div id="flash">
        <%= notice %>
      </div>
      <%= yield %>
    </div>
    <div id="footer">
      <p>Copyright &copy; 2012. RubyWeekend Depot</p>
      <p>Powered by <%= image_tag('rails.png') %>
    </div>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>

app/views/products/index.html.erb
<h2>Our Products</h2>
<div id="products">
  <% @products.each do |product| %>
    <div class="product">
      <%= link_to(product.name, product_path(product)) %><br>
      <%= image_tag(product.image.url(:main), :size => '80x100') %><br>
      <span class="price"><%= number_to_currency(product.price) %></span>
    </div>
  <% end %>
</div>

app/views/products/show.html.erb
<h2><%= @product.name %></h2>
<div class="left">
  <%= image_tag(@product.image.url(:main)) %>
</div>
<div class="right">
  <span>Price: <%= number_to_currency(@product.price) %></span>
  <%= form_for(@line_item) do |f| %>
    <%= hidden_field_tag(:product_id, @product.id) %>
    <%= f.label(:quantity) %><br>
    <%= f.select(:quantity, options_for_select((1..10).to_a)) %>
    <%= f.submit('Add to Order') %>
  <% end %>
</div>
<br clear="all">

<h4>About this product</h4>
<p><%= @product.description %></p>

app/views/searches/index.html.erb
<h2>Search Results</h2>
<h3>Found <%= @results.count %> results</h3>
<% @results.each do |product| %>
  <p><%= link_to(product.name, product_path(product)) %></p>
<% end %>

<%= paginate(@results) %>

app/views/site/about.html.erb
<h2>About Us</h2>

app/views/site/index.html.erb
<h1>Welcome to our Store!</h1>
<p>We have tons of products just for you! Pastrami short loin tongue, ham hock pancetta sirloin pork loin shankle bresaola rump pork beef chicken kielbasa. Drumstick bresaola boudin tenderloin meatloaf biltong short loin jowl, filet mignon fatback shank meatball. Salami andouille shoulder pork belly, pig swine ribeye prosciutto cow chicken biltong boudin corned beef shankle strip steak. Ball tip ham biltong tongue, rump fatback pork cow short ribs meatball andouille shoulder.</p>
<h3>Latest In Stock</h3>
<div id="products">
  <% @products.each do |product| %>
    <div class="product">
      <%= link_to(product.name, product_path(product)) %><br>
      <%= image_tag(product.image.url(:main), :size => '80x100') %><br>
      <span class="price"><%= number_to_currency(product.price) %></span>
    </div>
  <% end %>
</div>